spring:
  config:
    import: file:dev.env.yaml
  application:
      name: "PaymentService-CustomName-dev"
  datasource:
    url: "jdbc:mysql://localhost:3306/paymentservice?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"

# Test/development credentials
razorpay:
  key:
    id: ${razorpay.key.id}
    secret: ${razorpay.key.secret}

stripe:
  authentication:
    publishable_key: ${stripe.authentication.publishable_key}
    secret_key: ${stripe.authentication.secret_key}
  productId: ${stripe.productId}
  priceId: ${stripe.priceId}