spring:
  datasource:
    url: "jdbc:mysql://scaler-project-module-db.c8flxv6z8gbz.us-east-1.rds.amazonaws.com/paymentservice?createDatabaseIfNotExist=true"
    username: "admin"
    password: "adminadmin"

# Live/production credentials
razorpay:
  key:
    id: ""
    secret: ""

stripe:
  authentication:
    key: ""
    secret: ""
  productId: ""
  priceId: ""