spring:
  datasource:
##    MySQL
#    url: "jdbc:mysql://scaler-project-module-db.c8flxv6z8gbz.us-east-1.rds.amazonaws.com/paymentservice?createDatabaseIfNotExist=true"
#    username: "admin"
#    password: "adminadmin"

#    SQLite
#    https://www.baeldung.com/spring-boot-sqlite
#    https://www.baeldung.com/java-in-memory-databases
#    no need to create custom DataSource bean or custom dialect
    url: "jdbc:sqlite:paymentservice_prod_DB.sqlite"
#    this will create an in-memory database
#    url: "jdbc:sqlite:memory:paymentDB.sqlite"
    username: "sa"
    password: "sa"



# Live/production credentials
razorpay:
  key:
    id: ""
    secret: ""

stripe:
  authentication:
    publishable_key: ""
    secret_key: ""
  productId: ""
  priceId: ""